/* DATA TYPES */
enum types { NO_TYPE, INT, UINT, VOID };
/* RELATION OPERATORS */
enum relops { LT, LEQ, GT, GEQ, EQ, NEQ };
/* ITERATION OPERATORS */
enum itrops { INC, DEC };
/* SYMBOL TYPES */
enum kinds { NO_KIND = 0x1, REG = 0x2, LIT = 0x4, FUN = 0x8, VAR =0x10, PAR = 0x20 };
/* CONSTANTS FOR SIMULATION BOOL TYPE */
#define bool int
#define TRUE 1
#define FALSE 0
/* LENGTH OF SYMBOL TABLE */
#define SYMBOL_TABLE_LENGTH 64
/* AN INDICATION THAT SYMBOL HAS NO ATTRIBUTE*/
#define NO_ATR 0
/* NUMBER OF LAST AVAILABLE REGISTER */
#define LAST_WORKING_REG 12
/* REGISTER FOR STORING RETURN VALUE OF FUNCTION */
#define FUN_REG 13
/* BUFFER LENGTH FOR STORING ERROR MESSAGES */
#define CHAR_BUFFER_LENGTH 129
